server:
  port: 8899

# DataSource Config

spring:
  datasource:
    driver-class-name: org.h2.Driver
    schema: classpath:db/schema-h2.sql
    data: classpath:db/data-h2.sql
    url: jdbc:h2:mem:test
    username: root
    password: test

# Logger Config
logging:
  level:
    com.gihub.dreamyoung.mprelation: debug

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config: 
      db-config: 
          #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
         id-type: id_worker
          #驼峰下划线转换
         column-underline: true
  configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
     #查询时为null字段不加入，比如QueryWrapper中的应用
     call-setters-on-nulls: true
     lazyLoadingEnabled: true
     aggressiveLazyLoading: true