server:
  port: 8899

# DataSource Config

spring:
  datasource:    
    driver-class-name: com.mysql.jdbc.Driver        # 配置MySQL的驱动程序类
    url: jdbc:mysql://localhost:3306/mybatisplus    # 数据库连接地址
    username: root                                  # 数据库用户名
    password: root                                  # 数据库连接密码
    ################druid############################
    #type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
    #filters: stat,wall,log4j
    #dbcp2:                                          # 进行数据库连接池的配置
    #  min-idle: 10                                  # 数据库连接池的最小维持连接数    
    #  initial-size: 20                              # 初始化提供的连接数
    #  max-total: 50                                 # 最大的连接数
    #  max-wait-millis: 200                          # 等待连接获取的最大超时时间
    ################dbcp############################
    type: org.apache.commons.dbcp.BasicDataSource    # 配置当前要使用的数据源的操作类型
    filters: stat,wall,log4j
    dbcp:                                          # 进行数据库连接池的配置
      min-idle: 10                                  # 数据库连接池的最小维持连接数    
      initial-size: 20                              # 初始化提供的连接数
      max-total: 50                                 # 最大的连接数
      max-wait-millis: 200                          # 等待连接获取的最大超时时间

# Logger Config
logging:
  level:
    com.gihub.dreamyoung.mprelation: info

mybatis-plus:
  #如果xml映射文件的位置与mapper接口文件（mapper接口可以通过@Mapper被扫描或者配置类@MapperScan指定位置扫描）的位置不同目录，则需要指定
  #mapper-locations: classpath:/com/github/dreamyoung/mprelation/demo/mapper2/*Mapper.xml
  mapper-locations: classpath:/mapper/*Mapper.xml,com333.github.dreamyoung.mprelation.demo.mapper*/*Mapper.xml
  global-config: 
      db-config: 
          #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
         id-type: id_worker
          #驼峰下划线转换
         column-underline: true
  configuration:
     log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
     #查询时为null字段不加入，比如QueryWrapper中的应用
     call-setters-on-nulls: true
     lazyLoadingEnabled: true
     aggressiveLazyLoading: false